# -*- coding: utf-8 -*-
"""Copy of Irish_Parliamentary_Debate_NLP_LoRA_FineTuning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CC68S5WdeDApvpMZ-7L1TgvoL44XaStv
"""

!pip install requests pandas lxml beautifulsoup4 scikit-learn transformers torch --quiet

import requests
import pandas as pd
import time
import json
from bs4 import BeautifulSoup
from sklearn.model_selection import train_test_split

BASE_URL = "https://api.oireachtas.ie/v1"

all_debate_days = []
skip = 0
page_size = 50

while True:
    params = {
        "chamber_type": "house",
        "chamber": "dail",
        "date_start": "2024-07-01",
        "date_end": "2025-06-30",
        "limit": page_size,
        "skip": skip
    }
    resp = requests.get(BASE_URL + "/debates", params=params, timeout=30)
    resp.raise_for_status()
    page_data = resp.json()

    results = page_data["results"]
    if not results:
        break

    all_debate_days.extend(results)
    skip = skip + page_size
    print(f"Collected {len(all_debate_days)} sitting days so far...")
    time.sleep(0.3)

print(f"\nTotal Dail sitting days found: {len(all_debate_days)}")

all_usable_sections = []

for debate_day in all_debate_days:
    date = debate_day["contextDate"]
    sections = debate_day["debateRecord"]["debateSections"]

    for item in sections:
        sec = item["debateSection"]
        topic = sec["showAs"]
        has_content = sec["containsDebate"] and sec["formats"]["xml"] is not None
        speech_count = sec["counts"]["speechCount"]

        if has_content and speech_count > 0:
            xml_url = sec["formats"]["xml"]["uri"]
            all_usable_sections.append({
                "date": date,
                "topic": topic,
                "xml_url": xml_url,
                "speech_count": speech_count
            })

print(f"Total usable sections: {len(all_usable_sections)}")

all_rows = []

for i, section in enumerate(all_usable_sections):
    try:
        resp = requests.get(section["xml_url"], timeout=30)
        resp.raise_for_status()
        soup = BeautifulSoup(resp.text, "xml")

        heading_tag = soup.find("heading")
        topic = heading_tag.get_text(strip=True) if heading_tag else section["topic"]

        speeches = soup.find_all("speech")

        for sp in speeches:
            from_tag = sp.find("from")
            speaker_name = from_tag.get_text(strip=True) if from_tag else sp.get("by", "").replace("#", "")

            paragraphs = sp.find_all("p")
            text = " ".join(p.get_text(strip=True) for p in paragraphs)

            if len(text) > 20:
                all_rows.append({
                    "date": section["date"],
                    "topic": topic,
                    "speaker": speaker_name,
                    "text": text
                })

    except Exception as e:
        print(f"Skipped section {i} ({section['topic']}) due to error: {e}")

    if (i + 1) % 100 == 0 or (i + 1) == len(all_usable_sections):
        print(f"[{i+1}/{len(all_usable_sections)}] {len(all_rows)} speeches collected so far")
        pd.DataFrame(all_rows).to_csv("oireachtas_speeches_raw.csv", index=False)

    time.sleep(0.3)

df = pd.DataFrame(all_rows)
print(f"\nDONE. Total speeches collected: {len(df)}")
df.to_csv("oireachtas_speeches_raw.csv", index=False)

category_keywords = {
    "Defence & Security": ["defence", "military", "garda", "national security", "policing",
                             "air corps", "naval", "army", "council of defence", "air navigation",
                             "emergency planning", "drug dealing"],
    "Housing": ["housing", "accommodation", "tenant", "rent", "homeless",
                "vacant propert", "defective building", "regeneration", "derelict", "planning issue"],
    "Health": ["health", "hospital", "hse", "disability", "cancer", "treatment", "mental health",
               "eating disorder", "general practitioner", "medicinal product", "care service",
               "disabilities assessment"],
    "Education & Childcare": ["education", "childcare", "school", "student", "early childhood",
                               "special educational", "third level fees", "state examination"],
    "Social Welfare": ["social welfare", "child poverty", "pension", "benefit"],
    "Employment & Labour": ["work permit", "low pay", "employment", "labour market",
                             "industrial relations", "job losses"],
    "Transport & Infrastructure": ["transport", "road", "rail", "flood relief", "public transport",
                                     "bus service", "flood risk"],
    "Energy & Environment": ["energy", "renewable", "climate", "environment", "data centre",
                              "electric vehicle", "water charges"],
    "Foreign Affairs & Trade": ["middle east", "trade relations", "neutrality", "international",
                                 "foreign", "ukraine", "passport", "european council", "united nations"],
    "Economy & Business": ["business support", "economy", "enterprise", "finance", "tax",
                            "insurance", "industrial development", "national development plan",
                            "exchequer", "financial service", "financial instrument",
                            "public expenditure", "budget", "artificial intelligence"],
    "Agriculture & Rural": ["rural scheme", "agricultur", "farm", "animal disease"],
    "Justice & Legacy Issues": ["mother and baby homes", "redress", "human rights", "equality",
                                 "legal aid", "domestic, sexual and gender"],
    "Arts, Culture & Sport": ["sports funding", "sports facilit", "television licence", "arts",
                              "culture", "media", "commemorative"],
    "Government & Administration": ["cabinet committees", "taoiseach", "programme for government",
                                     "departmental", "local authorities", "legislative programme",
                                     "legislative measures", "state bodies", "community development",
                                     "grant payments", "ethics in public office", "office of public works",
                                     "official engagements"],
}

def assign_category(topic_title):
    topic_lower = topic_title.lower()
    for category, keywords in category_keywords.items():
        for kw in keywords:
            if kw in topic_lower:
                return category
    return "Other"

df["category"] = df["topic"].apply(assign_category)
print(df["category"].value_counts())

df_clean = df[df["category"] != "Other"].copy()
df_clean["text"] = df_clean["text"].str.strip()
df_clean["text_length"] = df_clean["text"].str.len()
df_clean = df_clean[df_clean["text_length"] >= 50]
df_clean = df_clean.drop_duplicates(subset=["text"])

print(f"Final dataset size: {len(df_clean)} speeches")
print(df_clean["category"].value_counts())

df_clean.to_csv("oireachtas_labeled_clean.csv", index=False)

train_df, temp_df = train_test_split(
    df_clean, test_size=0.30, stratify=df_clean["category"], random_state=42
)
val_df, test_df = train_test_split(
    temp_df, test_size=0.50, stratify=temp_df["category"], random_state=42
)

print(f"Train: {len(train_df)}, Val: {len(val_df)}, Test: {len(test_df)}")

train_df.to_csv("train.csv", index=False)
val_df.to_csv("val.csv", index=False)
test_df.to_csv("test.csv", index=False)

from transformers import pipeline
from sklearn.metrics import accuracy_score, classification_report

classifier = pipeline("zero-shot-classification", model="facebook/bart-large-mnli")
candidate_labels = list(train_df["category"].unique())

sample_test = test_df.sample(n=100, random_state=42).reset_index(drop=True)
predictions = []

for i, row in sample_test.iterrows():
    text = row["text"][:1000]
    result = classifier(text, candidate_labels)
    predictions.append(result["labels"][0])
    if (i + 1) % 10 == 0:
        print(f"[{i+1}/100] done")

sample_test["predicted_category"] = predictions
acc = accuracy_score(sample_test["category"], sample_test["predicted_category"])
print(f"\nZero-shot baseline accuracy: {acc:.3f}")
print(classification_report(sample_test["category"], sample_test["predicted_category"]))

import torch
print("CUDA available:", torch.cuda.is_available())
print("GPU:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "None")

!pip install peft accelerate bitsandbytes datasets --quiet

import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig

model_name = "Qwen/Qwen2.5-1.5B-Instruct"

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16
)

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    quantization_config=bnb_config,
    device_map="auto"
)

print("Model loaded on:", model.device)

def format_prompt(text, category=None):
    """
    Formats a speech as an instruction-following classification prompt.
    If category is given, includes it as the target answer (for training).
    If not, leaves it for the model to generate (for inference).
    """
    categories_str = ", ".join(candidate_labels)
    prompt = f"""Classify the following Irish parliamentary speech into exactly one policy category.

Categories: {categories_str}

Speech: {text[:800]}

Category:"""
    if category is not None:
        return prompt + f" {category}"
    return prompt

# Quick sanity check on one example
sample_prompt = format_prompt(train_df.iloc[0]["text"], train_df.iloc[0]["category"])
print(sample_prompt)

from datasets import Dataset

def build_dataset(df):
    prompts = [format_prompt(row["text"], row["category"]) for _, row in df.iterrows()]
    return Dataset.from_dict({"text": prompts})

train_dataset = build_dataset(train_df)
val_dataset = build_dataset(val_df)

def tokenize_fn(examples):
    result = tokenizer(
        examples["text"],
        truncation=True,
        max_length=512,
        padding="max_length"
    )
    result["labels"] = result["input_ids"].copy()
    return result

train_tokenized = train_dataset.map(tokenize_fn, batched=True, remove_columns=["text"])
val_tokenized = val_dataset.map(tokenize_fn, batched=True, remove_columns=["text"])

print(f"Train examples: {len(train_tokenized)}")
print(f"Val examples: {len(val_tokenized)}")

from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training

# Prepares the 4-bit model for training (handles some numerical stability details)
model = prepare_model_for_kbit_training(model)

lora_config = LoraConfig(
    r=16,                    # rank - controls adapter size/capacity
    lora_alpha=32,           # scaling factor
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj"],  # attention layers to adapt
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM"
)

model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

from transformers import TrainingArguments, Trainer, DataCollatorForLanguageModeling

training_args = TrainingArguments(
    output_dir="./lora_checkpoints",
    per_device_train_batch_size=4,
    gradient_accumulation_steps=4,
    num_train_epochs=3,
    learning_rate=2e-4,
    logging_steps=25,
    eval_strategy="epoch",
    save_strategy="epoch",
    fp16=True,
    report_to="none",
)

data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_tokenized,
    eval_dataset=val_tokenized,
    data_collator=data_collator,
)

trainer.train()

model.save_pretrained("./lora_finetuned_qwen")
tokenizer.save_pretrained("./lora_finetuned_qwen")
print("Adapter saved.")

from google.colab import drive
drive.mount('/content/drive')

!mkdir -p /content/drive/MyDrive/oireachtas_project
!cp -r ./lora_finetuned_qwen /content/drive/MyDrive/oireachtas_project/
print("Copied to Drive.")

import re

def predict_category(text, model, tokenizer):
    prompt = format_prompt(text)  # no category = model must generate one
    inputs = tokenizer(prompt, return_tensors="pt", truncation=True, max_length=512).to(model.device)

    with torch.no_grad():
        output = model.generate(
            **inputs,
            max_new_tokens=15,
            do_sample=False,
            pad_token_id=tokenizer.eos_token_id
        )

    generated = tokenizer.decode(output[0][inputs["input_ids"].shape[1]:], skip_special_tokens=True)
    generated = generated.strip()

    # Match generated text to the closest real category label
    for label in candidate_labels:
        if label.lower() in generated.lower():
            return label
    return generated  # fallback: return raw output if no match found

# Use the SAME sample_test set from the baseline for a fair comparison
model.eval()
lora_predictions = []

for i, row in sample_test.iterrows():
    pred = predict_category(row["text"], model, tokenizer)
    lora_predictions.append(pred)
    if (i + 1) % 10 == 0:
        print(f"[{i+1}/100] done")

sample_test["lora_predicted_category"] = lora_predictions

lora_acc = accuracy_score(sample_test["category"], sample_test["lora_predicted_category"])
print(f"Zero-shot baseline accuracy: 0.450")
print(f"LoRA fine-tuned accuracy: {lora_acc:.3f}")
print()
print(classification_report(sample_test["category"], sample_test["lora_predicted_category"]))

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    quantization_config=bnb_config,
    device_map="auto"
)
model = prepare_model_for_kbit_training(model)
model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

def build_masked_dataset(df, max_length=512):
    all_input_ids, all_attention_masks, all_labels = [], [], []

    for _, row in df.iterrows():
        prompt_only = format_prompt(row["text"])
        full_text = format_prompt(row["text"], row["category"])

        prompt_ids = tokenizer(prompt_only, truncation=True, max_length=max_length)["input_ids"]
        full_ids = tokenizer(full_text, truncation=True, max_length=max_length)["input_ids"]

        labels = full_ids.copy()
        prompt_len = min(len(prompt_ids), len(labels))
        for i in range(prompt_len):
            labels[i] = -100

        pad_len = max_length - len(full_ids)
        if pad_len > 0:
            full_ids = full_ids + [tokenizer.pad_token_id] * pad_len
            labels = labels + [-100] * pad_len
            attn = [1] * (max_length - pad_len) + [0] * pad_len
        else:
            full_ids = full_ids[:max_length]
            labels = labels[:max_length]
            attn = [1] * max_length

        all_input_ids.append(full_ids)
        all_attention_masks.append(attn)
        all_labels.append(labels)

    return Dataset.from_dict({
        "input_ids": all_input_ids,
        "attention_mask": all_attention_masks,
        "labels": all_labels
    })

train_tokenized = build_masked_dataset(train_df)
val_tokenized = build_masked_dataset(val_df)
print(f"Train: {len(train_tokenized)}, Val: {len(val_tokenized)}")

from transformers import default_data_collator

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_tokenized,
    eval_dataset=val_tokenized,
    data_collator=default_data_collator,
)

trainer.train()

model.save_pretrained("./lora_finetuned_qwen_v2")
tokenizer.save_pretrained("./lora_finetuned_qwen_v2")

!cp -r ./lora_finetuned_qwen_v2 /content/drive/MyDrive/oireachtas_project/
print("Saved and copied to Drive.")

model.eval()
lora_predictions_v2 = []

for i, row in sample_test.iterrows():
    pred = predict_category(row["text"], model, tokenizer)
    lora_predictions_v2.append(pred)
    if (i + 1) % 10 == 0:
        print(f"[{i+1}/100] done")

sample_test["lora_v2_predicted_category"] = lora_predictions_v2

lora_v2_acc = accuracy_score(sample_test["category"], sample_test["lora_v2_predicted_category"])

print(f"Zero-shot baseline accuracy:        0.450")
print(f"LoRA v1 (buggy, unmasked labels):    0.280")
print(f"LoRA v2 (fixed, masked labels):      {lora_v2_acc:.3f}")
print()
print(classification_report(sample_test["category"], sample_test["lora_v2_predicted_category"]))

# Check how many predictions didn't cleanly match one of the 14 real categories
invalid_predictions = sample_test[~sample_test["lora_v2_predicted_category"].isin(candidate_labels)]
print(f"Predictions that didn't match a real category: {len(invalid_predictions)} out of 100")
print()
for idx, row in invalid_predictions.iterrows():
    print(f"True: {row['category']} | Generated: {row['lora_v2_predicted_category'][:80]}")

# Pick 3 examples the model got right, from different categories, for explainability
correct_predictions = sample_test[
    sample_test["category"] == sample_test["lora_v2_predicted_category"]
]

examples_to_explain = correct_predictions.groupby("category").first().reset_index().head(3)
print(examples_to_explain[["category", "text"]].to_string())

import numpy as np

def explain_prediction(text, true_category, model, tokenizer, num_chunks=10):
    """
    Splits the speech into chunks, removes each one at a time, and measures
    how much the model's confidence in the correct category drops.
    Bigger drop = that chunk mattered more for the prediction.
    """
    words = text[:800].split()
    chunk_size = max(1, len(words) // num_chunks)
    chunks = [" ".join(words[i:i+chunk_size]) for i in range(0, len(words), chunk_size)]

    def get_category_score(input_text):
        prompt = format_prompt(input_text)
        inputs = tokenizer(prompt, return_tensors="pt", truncation=True, max_length=512).to(model.device)
        with torch.no_grad():
            outputs = model(**inputs)
        logits = outputs.logits[0, -1, :]  # last token's logits
        category_token_id = tokenizer.encode(" " + true_category.split()[0], add_special_tokens=False)[0]
        return torch.softmax(logits, dim=-1)[category_token_id].item()

    baseline_score = get_category_score(text[:800])

    importances = []
    for i in range(len(chunks)):
        modified = chunks[:i] + chunks[i+1:]
        modified_text = " ".join(modified)
        score = get_category_score(modified_text)
        importance = baseline_score - score  # how much confidence dropped without this chunk
        importances.append((chunks[i], importance))

    return sorted(importances, key=lambda x: -x[1])

# Run on one example
example_row = examples_to_explain.iloc[0]
print(f"Category: {example_row['category']}\n")
results = explain_prediction(example_row["text"], example_row["category"], model, tokenizer)

print("Most influential chunks (highest impact first):\n")
for chunk, importance in results[:5]:
    print(f"[impact: {importance:+.4f}] {chunk[:100]}...")

all_explanations = []

for idx, row in examples_to_explain.iterrows():
    print(f"\n{'='*60}")
    print(f"Category: {row['category']}")
    print('='*60)

    results = explain_prediction(row["text"], row["category"], model, tokenizer)

    print("\nTop 5 influential chunks:\n")
    for chunk, importance in results[:5]:
        print(f"[impact: {importance:+.4f}] {chunk[:100]}...")

    all_explanations.append({
        "category": row["category"],
        "text": row["text"][:800],
        "top_chunks": results[:5]
    })

print("\n\nDone - explanations captured for all 3 examples.")

